"""Generate basemap_towns.rs from Census cartographic place boundaries.

Standalone, additive companion to generate_basemap_data.py: emits ONLY the
dense US small-town label set (cb_2023_us_place_500k — ~32k incorporated
places and CDPs) so meteorologists can call out the tiny towns a storm is
approaching (the GR2Analyst basemap look). Ranks by land area:
  7: ALAND > 50 km^2   (small cities)
  8: ALAND > 10 km^2   (towns)
  9: everything else   (villages/CDPs)
Label point = polygon bbox center. Sorted rank, then area desc, so the
renderer's label budget naturally prefers bigger towns.
"""

import struct
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "work" / "basemap_sources" / "cb_2023_us_place_500k.zip"
OUT = ROOT / "crates" / "app_ui" / "src" / "basemap_towns.rs"


def read_member(suffix):
    with zipfile.ZipFile(SOURCE) as archive:
        name = next(n for n in archive.namelist() if n.endswith(suffix))
        return archive.read(name)


def read_dbf():
    data = read_member(".dbf")
    header_len = struct.unpack_from("<H", data, 8)[0]
    record_len = struct.unpack_from("<H", data, 10)[0]
    record_count = struct.unpack_from("<I", data, 4)[0]
    fields = []
    pos = 32
    while data[pos] != 0x0D:
        name = data[pos : pos + 11].split(b"\x00")[0].decode("ascii")
        ftype = chr(data[pos + 11])
        length = data[pos + 16]
        fields.append((name, ftype, length))
        pos += 32
    records = []
    for i in range(record_count):
        start = header_len + i * record_len
        row = {}
        offset = start + 1
        for name, ftype, length in fields:
            raw = data[offset : offset + length]
            offset += length
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError:
                text = raw.decode("latin-1", "ignore")
            text = text.replace(chr(0), "").strip()
            if ftype == "N":
                try:
                    row[name] = float(text) if text else 0.0
                except ValueError:
                    row[name] = 0.0
            else:
                row[name] = text
        records.append(row)
    return records


def read_shape_bboxes():
    data = read_member(".shp")
    bboxes = []
    pos = 100
    while pos + 8 <= len(data):
        content_words = struct.unpack_from(">i", data, pos + 4)[0]
        content_len = content_words * 2
        start = pos + 8
        shape_type = struct.unpack_from("<i", data, start)[0]
        if shape_type in (3, 5):  # polyline / polygon: bbox follows type
            xmin, ymin, xmax, ymax = struct.unpack_from("<4d", data, start + 4)
            bboxes.append((xmin, ymin, xmax, ymax))
        else:
            bboxes.append(None)
        pos = start + content_len
    return bboxes


def escape(name):
    import unicodedata

    cleaned = []
    for ch in name:
        if ch in ('"', "\\"):
            continue
        # Drop control/format characters (e.g. soft hyphens) that trip
        # clippy's invisible-character lint.
        if unicodedata.category(ch) in ("Cc", "Cf"):
            continue
        cleaned.append(ch)
    return "".join(cleaned).strip()


def main():
    records = read_dbf()
    bboxes = read_shape_bboxes()
    towns = []
    for record, bbox in zip(records, bboxes):
        if not bbox:
            continue
        name = escape(record.get("NAME", ""))
        if not name:
            continue
        aland = float(record.get("ALAND", 0.0))
        lon = (bbox[0] + bbox[2]) / 2.0
        lat = (bbox[1] + bbox[3]) / 2.0
        if aland > 50e6:
            rank = 7
        elif aland > 10e6:
            rank = 8
        else:
            rank = 9
        towns.append((rank, -aland, name, lon, lat))
    towns.sort()
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("// Generated by tools/generate_town_labels.py\n")
        handle.write(
            "// Source: US Census Bureau cartographic boundaries (cb_2023_us_place_500k).\n\n"
        )
        handle.write("#![allow(clippy::approx_constant, clippy::excessive_precision)]\n\n")
        handle.write("use crate::basemap_data::BasemapLabel;\n\n")
        handle.write("#[rustfmt::skip]\n")
        handle.write("pub const BASEMAP_US_TOWN_LABELS: &[BasemapLabel] = &[\n")
        for rank, _, name, lon, lat in towns:
            handle.write(
                f'    BasemapLabel {{ name: "{name}", lon: {lon:.5}, lat: {lat:.5}, rank: {rank} }},\n'
            )
        handle.write("];\n")
    print(f"wrote {len(towns)} towns to {OUT}")


if __name__ == "__main__":
    main()
